export const accents = [
    "American", "British", "Australian", "Canadian", "Irish",
    "Scottish", "Welsh", "New Zealand", "South African", "Indian",
    "Pakistani", "Bangladeshi", "Nigerian", "Kenyan", "Ghanaian",
    "Jamaican", "Trinidadian", "Barbadian", "Haitian", "Cuban",
    "Dominican", "Puerto Rican", "Mexican", "Brazilian", "Argentinian",
    "Chilean", "Colombian", "Peruvian", "Venezuelan", "Ecuadorian",
    "Bolivian", "Uruguayan", "Paraguayan", "Panamanian", "Costa Rican",
    "Nicaraguan", "Honduran", "Guatemalan", "El Salvadoran", "Belizean",
    "Filipino", "Malaysian", "Singaporean", "Indonesian", "Thai",
    "Vietnamese", "Cambodian", "Laotian", "Burmese", "Japanese",
    "Korean", "Chinese", "Mongolian", "Nepalese", "Sri Lankan",
    "Saudi Arabian", "Emirati", "Qatari", "Kuwaiti", "Omani",
    "Jordanian", "Lebanese", "Syrian", "Iraqi", "Iranian",
    "Afghan", "Turkish", "Egyptian", "Moroccan", "Algerian",
    "Tunisian", "Libyan", "Sudanese", "Ethiopian", "Somali",
    "Ugandan", "Rwandan", "Congolese", "Angolan", "Mozambican",
    "Zambian", "Zimbabwean", "Botswanan", "Namibian", "Malian",
    "Senegalese", "Ivorian", "Liberian", "Sierra Leonean", "Guinean",
    "Bissau-Guinean", "Gabonese", "Cameroonian", "Chadian", "South Sudanese",
    "Russian", "Ukrainian", "Belarusian", "Polish", "Czech",
    "Slovak", "Hungarian", "Romanian", "Bulgarian", "Serbian",
    "Croatian", "Bosnian", "Slovenian", "Macedonian", "Albanian",
    "Greek", "Cypriot", "Maltese", "Italian", "Spanish",
    "Portuguese", "French", "Belgian", "Swiss", "Luxembourgish",
    "Austrian", "German", "Dutch", "Danish", "Norwegian",
    "Swedish", "Finnish", "Icelandic", "Estonian", "Latvian",
    "Lithuanian", "Georgian", "Armenian", "Azerbaijani", "Kazakh"
];

export const animals = [
    "Lion", "Tiger", "Elephant", "Leopard", "Cheetah",
    "Giraffe", "Zebra", "Rhinoceros", "Hippopotamus", "Gorilla",
    "Chimpanzee", "Orangutan", "Wolf", "Fox", "Bear",
    "Polar Bear", "Koala", "Kangaroo", "Wallaby", "Panda",
    "Red Panda", "Sloth", "Armadillo", "Anteater", "Buffalo",
    "Bison", "Aardvark", "Hyena", "Meerkat", "Mongoose",
    "Raccoon", "Skunk", "Weasel", "Otter", "Beaver",
    "Mole", "Squirrel", "Chipmunk", "Rat", "Mouse",
    "Rabbit", "Hare", "Shrew", "Bat", "Hedgehog",
    "Elephant Seal", "Sea Lion", "Walrus", "Manatee", "Dugong",
    "Whale", "Dolphin", "Porpoise", "Shark", "Ray",
    "Eel", "Seahorse", "Clownfish", "Salmon", "Trout",
    "Tuna", "Halibut", "Marlin", "Barracuda", "Pufferfish",
    "Starfish", "Sea Urchin", "Jellyfish", "Octopus", "Squid",
    "Lobster", "Crab", "Shrimp", "Oyster", "Clam",
    "Snail", "Scallop", "Mussel", "Coral", "Anemone",
    "Parrot", "Eagle", "Hawk", "Falcon", "Owl",
    "Vulture", "Flamingo", "Swan", "Goose", "Duck",
    "Penguin", "Albatross", "Pelican", "Stork", "Heron",
    "Crane", "Sparrow", "Robin", "Blue Jay", "Cardinal",
    "Canary", "Parakeet", "Cockatoo", "Peacock", "Ostrich",
    "Emu", "Kookaburra", "Kingfisher", "Woodpecker", "Hummingbird",
    "Hornbill", "Toucan", "Pigeon", "Dove", "Crow",
    "Raven", "Magpie", "Lark", "Finch", "Warbler",
    "Swallow", "Blackbird", "Thrush", "Wren", "Sparrowhawk",
    "Chickadee", "Nuthatch", "Goldfinch", "Waxwing", "Tanager",
    "Bunting", "Grosbeak", "Flycatcher", "Phoebe", "Vireo",
    "Caterpillar", "Butterfly", "Moth", "Beetle", "Dragonfly",
    "Ladybug", "Ant", "Bee", "Wasp", "Hornet",
    "Spider", "Scorpion", "Centipede", "Millipede", "Earthworm",
    "Leech", "Slug", "Praying Mantis", "Grasshopper", "Cricket",
    "Cockroach", "Termite", "Flea", "Tick", "Mosquito",
    "Fly", "Firefly", "Glowworm", "Beetle", "Stick Insect",
    "Frog", "Toad", "Newt", "Salamander", "Lizard",
    "Snake", "Turtle", "Tortoise", "Crocodile", "Alligator",
    "Iguana", "Chameleon", "Gecko", "Skink", "Monitor Lizard",
    "Python", "Boa Constrictor", "Rattlesnake", "Anaconda", "Cobra",
    "Sea Turtle", "Komodo Dragon", "Gila Monster", "Armadillo Lizard", "Agama",
    "Thorny Devil", "Frilled Lizard", "Uromastyx", "Water Dragon", "Anole",
    "Tegu", "Chuckwalla", "Leopard Gecko", "Crested Gecko", "Bearded Dragon",
    "Axolotl", "Mudskipper", "Coelacanth", "Sturgeon", "Catfish",
    "Carp", "Goldfish", "Koi", "Guppy", "Betta",
    "Angelfish", "Discus", "Pirahna", "Electric Eel", "Moray Eel",
    "Stonefish", "Lionfish", "Triggerfish", "Clown Triggerfish", "Surgeonfish",
    "Tang", "Butterflyfish", "Seadragon", "Pipefish", "Mackerel",
    "Herring", "Sardine", "Anchovy", "Gar", "Bowfin",
    "Tarpon", "Barramundi", "Mahi Mahi", "Swordfish", "Sailfish",
    "Flying Fish", "Mudfish", "Goby", "Blenny", "Wrasse"
];

export const christmas = [
    "Santa Claus", "Reindeer", "Christmas Tree", "Stocking", "Gingerbread Man",
    "Snowman", "Christmas Lights", "Ornaments", "Elf", "North Pole",
    "Candy Cane", "Christmas Carols", "Sleigh", "Mistletoe", "Wrapping Presents",
    "Christmas Eve", "Hot Cocoa", "Eggnog", "Christmas Cookies", "Wreath",
    "Fireplace", "Chimney", "Snowball Fight", "Ice Skating", "Sledding",
    "Gift Exchange", "Holly", "Jingle Bells", "Christmas Cards", "Nativity Scene",
    "Toy Train", "Santa's Workshop", "Christmas Parade", "Yule Log", "Rudolph",
    "Frosty", "Christmas Dinner", "Sugar Plums", "Christmas Sweater", "Reindeer Games",
    "Baking Cookies", "Christmas Morning", "Advent Calendar", "Christmas Market", "Noel",
    "Christmas Spirit", "Silent Night", "Christmas Stocking", "Gift Wrapping", "Christmas Decorations",
    "North Star", "Secret Santa", "Sleigh Ride", "Making Snow Angels", "Trimming the Tree",
    "Christmas Movies", "Holiday Feast", "Midnight Mass", "Nutcracker", "Poinsettia",
    "Twelve Days of Christmas", "Figgy Pudding", "Caroling", "Holiday Shopping", "Snowflakes",
    "Christmas Pudding", "Ice Sculptures", "Decorating the Tree", "Christmas Party", "Ugly Sweater",
    "Christmas Feast", "Snow Globe", "Reindeer Antlers", "Christmas Stocking", "Bells",
    "Christmas Wreath", "Frost", "Icicles", "Gingerbread House", "Holiday Lights",
    "Peppermint Bark", "Winter Wonderland", "Pine Cones", "Christmas Turkey", "Reindeer Sleigh",
    "Santa's Hat", "Snow Covered Trees", "Winter Boots", "Holiday Season", "Christmas Crackers",
    "Festive Cheer", "Jolly", "Christmas Star", "Holiday Music", "Christmas Bells",
    "Christmas Roast", "Christmas Grotto", "Santa's Reindeer", "Snowy Night", "Winter Solstice",
    "Roasting Chestnuts", "Building a Snowman", "Exchanging Gifts", "Holiday Greetings", "Christmas Countdown",
    "Christmas Miracle", "Christmas Spirit", "Reindeer Ride", "North Pole Expedition", "Christmas Stocking",
    "Ringing Bells", "Christmas Eve Dinner", "Sipping Eggnog", "Listening to Carols", "Watching Christmas Movies",
    "Stringing Lights", "Hanging Ornaments", "Baking Gingerbread", "Christmas Baking", "Secret Santa Exchange",
    "Santa's Little Helper", "Holiday Baking", "Spreading Cheer", "Singing Carols", "Christmas Shopping",
    "Holiday Tradition", "Opening Presents", "Christmas Hat", "Red Nose", "Christmas Magic",
    "Winter Chill", "Frosty Windows", "Glistening Snow", "Holiday Celebration", "Snow Angels",
    "Festive Gathering", "Winter Festivities", "Santa's List", "Checking it Twice", "Warm Fireplace",
    "Hanging Stockings", "Christmas Candles", "Yule Time", "Snowfall", "Holiday Cheers",
    "Decorative Lights", "Reindeer Run", "Christmas Elves", "Winter Scarf", "Holiday Wishes",
    "Santa's Arrival", "Twinkling Lights", "Christmas Day", "Christmas Treats", "Snow Fort",
    "Holiday Cheers", "Christmas Feast", "Santa's Beard", "Snow Boots", "Christmas Jingles",
    "Spreading Joy", "Holiday Sweets", "Cuddling by the Fire", "Ice Skating Rink", "Holiday Parade",
    "Glistening Icicles", "Baking Festive Treats", "Christmas Hymns", "Holiday Mirth", "Reindeer Tracks",
    "Warm Blankets", "Holiday Decorations", "Christmas Joy", "Reindeer Antlers", "Santa's Workshop",
    "Holiday Excitement", "Christmas Eve Story", "Hanging Mistletoe", "Presents Under the Tree", "Santa's Elves",
    "Christmas Tidings", "Hot Chocolate", "Reindeer Games", "Holiday Joy", "Christmas Fireworks",
    "Christmas Countdown", "Wrapping Paper", "Festive Favors", "Gingerbread Village", "Reindeer Parade",
    "Christmas Lullabies", "Snowy Path", "Cozy Fireplace", "Holiday Spirit", "Pine Tree",
    "Holiday Traditions", "Christmas Mugs", "Santa's Sleigh Bells", "Winter Wonderland", "Holiday Baking",
    "Candy Cane Lane", "Holiday Serenades", "Christmas Carriage", "Holiday Snowfall", "Wintertime Fun",
    "Festive Lights", "Santa's Helper", "Christmas Stockings", "Wintertime Delights", "Snowy Landscape",
    "Warm Hugs", "Christmas Charades", "Gingerbread Decorating", "Santa's Gift Bag", "Holiday Fun",
    "Winter Activities", "Season's Greetings", "Christmas Dreams", "Santa's Big Night", "Holiday Desserts",
    "Merry Making", "Christmas Music", "Holiday Cheers", "Santa's Ho Ho Ho", "Festive Christmas Eve",
    "Snowy Christmas", "Christmas Traditions", "Festive Joy", "Christmas Cuddles", "Holiday Tidings",
    "Santa's Journey", "Christmas Eve Magic", "Reindeer Sleigh Ride", "Christmas Excitement", "Holiday Love",
    "Gingerbread Men", "Seasonal Celebration", "Winter Joy", "Christmas Eve Fun", "Holiday Excitement",
    "Pine Scent", "Festive Treats", "Christmas Spirit", "Holiday Baking", "Santa's Laugh",
    "Warm Cider", "Winter Fest", "Snowman Building", "Christmas Warmth", "Holiday Sparkle",
    "Snowy Forest", "Christmas Tree Decorating", "Santa's Sack", "Christmas Delights", "Cozy Night",
    "Christmas Breakfast", "Holiday Sweets", "Twinkling Stars", "Holiday Merriment", "Santa's Helpers",
    "Christmas Countdown", "Holiday Memories", "Snowy Night", "Christmas Eve Excitement", "Santa's Flight",
    "Merry Christmas", "Holiday Warmth", "Christmas Night", "Christmas Stockings", "Holiday Glow",
    "Snowball Fun", "Christmas Candies", "Holiday Mugs", "Winter Cheer", "Christmas Stocking Stuffers",
    "Santa's Suit", "Christmas Feast", "Holiday Laughter", "Christmas Cookies", "Christmas Eve Tradition",
    "Festive Gatherings", "Reindeer Dash", "Christmas Morning Joy", "Christmas Scene", "Santa's Reindeer",
    "Warm Mittens", "Christmas Lights", "Holiday Eve", "Santa's Elves", "Christmas Harmony",
    "Snowy Mornings", "Santa's Boots", "Holiday Season", "Christmas Frost", "Holiday Fun",
    "Christmas Countdown", "Santa's Chimney", "Reindeer Flight", "Santa's Reindeer Team", "Christmas Sleigh"
];

export const actItOut = [
    "Dancing", "Singing", "Jumping", "Running", "Cooking",
    "Driving a Car", "Swimming", "Playing Guitar", "Reading a Book", "Writing",
    "Typing", "Fishing", "Walking the Dog", "Riding a Bike", "Playing Basketball",
    "Flying a Kite", "Painting", "Taking Photos", "Climbing a Mountain", "Mowing the Lawn",
    "Playing Soccer", "Washing Dishes", "Sweeping the Floor", "Vacuuming", "Playing the Piano",
    "Jogging", "Skating", "Skiing", "Snowboarding", "Surfing",
    "Sailing", "Paddling a Canoe", "Boxing", "Doing Yoga", "Meditating",
    "Doing Push-ups", "Weightlifting", "Cheerleading", "Playing Tennis", "Golfing",
    "Gardening", "Feeding Birds", "Doing Laundry", "Ironing Clothes", "Shopping",
    "Playing Chess", "Watching TV", "Listening to Music", "Hiking", "Fishing",
    "Setting Up a Tent", "Making a Campfire", "Roasting Marshmallows", "Playing Cards", "Playing Video Games",
    "Opening a Gift", "Wrapping Presents", "Blowing Up Balloons", "Cutting Hair", "Brushing Teeth",
    "Combing Hair", "Shaving", "Taking a Shower", "Baking a Cake", "Eating",
    "Drinking", "Sneezing", "Coughing", "Yawning", "Laughing",
    "Crying", "Smiling", "Winking", "Frowning", "Whistling",
    "Snapping Fingers", "Clapping Hands", "Waving", "Pointing", "Nodding",
    "Shaking Head", "Stretching", "Yawning", "Sleeping", "Dreaming",
    "Waking Up", "Brushing Hair", "Getting Dressed", "Tying Shoelaces", "Making the Bed",
    "Brushing Pet", "Taking Out the Trash", "Washing Car", "Playing with Dog", "Feeding Fish",
    "Riding a Horse", "Playing the Drums", "Playing the Violin", "Hula Hooping", "Juggling",
    "Playing Hide and Seek", "Playing Tag", "Jumping Rope", "Playing Hopscotch", "Blowing Bubbles",
    "Flying a Drone", "Building a Sandcastle", "Sunbathing", "Collecting Seashells", "Swimming in the Ocean",
    "Building a Snowman", "Having a Snowball Fight", "Sledding", "Ice Skating", "Decorating a Christmas Tree",
    "Carving a Pumpkin", "Handing Out Candy", "Trick or Treating", "Watching Fireworks", "Making a Toast",
    "Proposing Marriage", "Kissing", "Hugging", "Waving Goodbye", "Welcoming",
    "Reading a Map", "Driving a Boat", "Paddling a Kayak", "Scuba Diving", "Snorkeling",
    "Paragliding", "Skydiving", "Flying a Helicopter", "Flying a Plane", "Riding a Scooter",
    "Riding a Skateboard", "Performing a Magic Trick", "Balancing on One Foot", "Doing a Cartwheel", "Turning a Somersault",
    "Doing a Handstand", "Walking on Stilts", "Juggling Balls", "Throwing a Frisbee", "Playing Frisbee",
    "Blowing Out Candles", "Cutting a Cake", "Eating Ice Cream", "Licking a Lollipop", "Chewing Gum",
    "Brushing a Doll's Hair", "Playing with a Toy Car", "Building with Blocks", "Playing with Playdough", "Drawing",
    "Coloring", "Cutting with Scissors", "Gluing", "Sewing", "Knitting",
    "Crocheting", "Embroidery", "Quilting", "Playing the Harmonica", "Playing the Trumpet",
    "Playing the Flute", "Playing the Accordion", "Reading the Newspaper", "Writing a Letter", "Sending an Email",
    "Talking on the Phone", "Texting", "Using a Computer", "Using a Tablet", "Taking a Selfie",
    "Doing a Puzzle", "Solving a Rubik's Cube", "Playing Monopoly", "Playing Scrabble", "Playing Checkers",
    "Playing Jenga", "Playing Twister", "Playing Darts", "Throwing a Ball", "Catching a Ball",
    "Kicking a Ball", "Bouncing a Ball", "Dribbling a Ball", "Shooting a Basketball", "Serving a Tennis Ball",
    "Serving a Volleyball", "Kicking a Soccer Ball", "Throwing a Football", "Batting in Baseball", "Pitching a Baseball",
    "Hitting a Home Run", "Sliding into Base", "Riding a Carousel", "Riding a Ferris Wheel", "Going Down a Slide",
    "Swinging on a Swing", "Playing on a See-Saw", "Riding a Roller Coaster", "Eating Cotton Candy", "Eating Popcorn",
    "Eating a Hotdog", "Sipping from a Straw", "Holding a Cup", "Pouring a Drink", "Mixing a Drink",
    "Making a Smoothie", "Eating Spaghetti", "Eating Sushi", "Chopping Vegetables", "Peeling an Orange",
    "Peeling a Banana", "Stirring Soup", "Frying Eggs", "Cooking Spaghetti", "Grilling Meat",
    "Making a Salad", "Eating a Sandwich", "Drinking Coffee", "Making Tea", "Baking Bread",
    "Rolling Dough", "Playing with a Yo-Yo", "Spinning a Top", "Playing Marbles", "Jumping on a Trampoline",
    "Playing Dodgeball", "Flying a Paper Airplane", "Folding Origami", "Playing with a Remote-Controlled Car", "Driving a Toy Train",
    "Setting Up a Dollhouse", "Changing a Doll's Clothes", "Feeding a Doll", "Pretending to Be a Superhero", "Pretending to Be a Pirate",
    "Pretending to Be a Princess", "Pretending to Be a Doctor", "Pretending to Be a Teacher", "Pretending to Be a Chef", "Pretending to Be a Firefighter",
    "Pretending to Be a Police Officer", "Pretending to Be a Farmer", "Pretending to Be an Astronaut", "Pretending to Be a Scientist", "Pretending to Be an Artist",
    "Pretending to Be a Pilot", "Pretending to Be a Sailor", "Pretending to Be a Soldier", "Pretending to Be a Detective", "Pretending to Be a Spy",
    "Pretending to Be a Ninja", "Pretending to Be a Samurai", "Pretending to Be a Knight", "Pretending to Be a Cowboy", "Pretending to Be an Indian",
    "Pretending to Be a Mermaid", "Pretending to Be a Fairy", "Pretending to Be a Ghost", "Pretending to Be a Vampire", "Pretending to Be a Werewolf",
    "Pretending to Be a Zombie", "Pretending to Be a Witch", "Pretending to Be a Wizard", "Pretending to Be a Dragon", "Pretending to Be a Dinosaur",
    "Pretending to Be an Alien", "Pretending to Be a Robot", "Pretending to Be a Monster", "Pretending to Be a Giant", "Pretending to Be a Unicorn",
    "Pretending to Be a Pegasus", "Pretending to Be a Griffin", "Pretending to Be a Phoenix", "Pretending to Be a Genie", "Pretending to Be a Gnome",
    "Pretending to Be an Elf", "Pretending to Be a Troll", "Pretending to Be a Goblin", "Pretending to Be a Dwarf", "Pretending to Be a Centaur",
    "Pretending to Be a Satyr", "Pretending to Be a Minotaur", "Pretending to Be a Cyclops", "Pretending to Be a Kraken", "Pretending to Be a Hydra",
    "Pretending to Be a Chimera", "Pretending to Be a Basilisk", "Pretending to Be a Manticore", "Pretending to Be a Sphinx", "Pretending to Be a Siren",
    "Pretending to Be a Harpy", "Pretending to Be a Medusa", "Pretending to Be a Gorgon", "Pretending to Be a Cerberus", "Pretending to Be a Pegasus",
    "Pretending to Be a Leviathan", "Pretending to Be a Unicorn", "Pretending to Be a Dragon", "Pretending to Be a Phoenix", "Pretending to Be a Hydra"
];

export const emotions =[
    "Happy", "Sad", "Angry", "Excited", "Scared",
    "Surprised", "Nervous", "Confused", "Bored", "Lonely",
    "Proud", "Ashamed", "Embarrassed", "Jealous", "Grateful",
    "Guilty", "Anxious", "Hopeful", "Frustrated", "Disappointed",
    "Content", "Shocked", "Envious", "Relaxed", "Relieved",
    "Worried", "Curious", "Amazed", "Annoyed", "Cheerful",
    "Depressed", "Disgusted", "Eager", "Enthusiastic", "Furious",
    "Horrified", "Indifferent", "Jubilant", "Overwhelmed", "Peaceful",
    "Regretful", "Satisfied", "Smug", "Stressed", "Suspicious",
    "Tender", "Thoughtful", "Touched", "Uncomfortable", "Unhappy",
    "Upset", "Vengeful", "Yearning", "Affectionate", "Agitated",
    "Alarmed", "Aloof", "Apathetic", "Aroused", "Bewildered",
    "Blissful", "Calm", "Captivated", "Charmed", "Compassionate",
    "Concerned", "Contemptuous", "Crushed", "Defeated", "Dejected",
    "Delighted", "Desperate", "Devastated", "Disillusioned", "Distraught",
    "Distressed", "Elated", "Exasperated", "Exhilarated", "Frightened",
    "Grumpy", "Hateful", "Hurt", "Impatient", "Impressed",
    "Infatuated", "Inspired", "Irritated", "Joyful", "Kind",
    "Love", "Mad", "Melancholic", "Miserable", "Mortified",
    "Moved", "Optimistic", "Overjoyed", "Panicked", "Passionate",
    "Pensive", "Perplexed", "Pleased", "Puzzled", "Raging",
    "Regretful", "Rejected", "Resentful", "Resigned", "Restless",
    "Sorrowful", "Startled", "Sympathetic", "Terrified", "Thrilled",
    "Triumphant", "Troubled", "Uneasy", "Uplifted", "Valiant",
    "Vulnerable", "Warm", "Weary", "Wistful", "Zealous",
    "Admiration", "Adoration", "Affection", "Agony", "Alarm",
    "Alienation", "Ambivalence", "Anguish", "Anticipation", "Apprehension",
    "Arrogance", "Astonishment", "Attraction", "Aversion", "Benevolence",
    "Bitterness", "Blame", "Calmness", "Chagrin", "Clarity",
    "Compassion", "Confidence", "Consolation", "Contempt", "Contentment",
    "Courage", "Cruelty", "Defiance", "Despair", "Determination",
    "Devotion", "Disdain", "Disgust", "Disheartened", "Displeasure",
    "Dismay", "Doubt", "Ecstasy", "Empathy", "Emptiness",
    "Enlightenment", "Euphoria", "Fear", "Fondness", "Frenzy",
    "Friendliness", "Glee", "Gloom", "Grief", "Hatred",
    "Helplessness", "Hope", "Hostility", "Hysteria", "Idolization",
    "Insecurity", "Inspiration", "Irritation", "Jubilation", "Kindness",
    "Liveliness", "Longing", "Lust", "Melancholy", "Misery",
    "Nostalgia", "Obsession", "Outrage", "Pain", "Patience",
    "Pity", "Rage", "Rapture", "Rejection", "Reluctance",
    "Remorse", "Resentment", "Respect", "Sadness", "Satisfaction",
    "Scorn", "Serenity", "Shock", "Sorrow", "Spite",
    "Suffering", "Sympathy", "Tenderness", "Terror", "Tranquility",
    "Trust", "Uncertainty", "Wonder", "Yearning", "Zeal",
    "Anticipating", "Appreciating", "Approving", "Beaming", "Blushing",
    "Bouncing", "Bragging", "Caring", "Comforting", "Complaining",
    "Cowering", "Cringing", "Daydreaming", "Delighting", "Desiring",
    "Detesting", "Dreading", "Ducking", "Embracing", "Encouraging",
    "Fantasizing", "Flinching", "Frowning", "Gasping", "Grinning",
    "Groaning", "Grumbling", "Gulping", "Hesitating", "Hugging",
    "Humming", "Leaping", "Loving", "Murmuring", "Musing",
    "Pacing", "Pouting", "Praying", "Rejoicing", "Savoring",
    "Sighing", "Snickering", "Sniffling", "Snoring", "Sobbing",
    "Squealing", "Startling", "Swaying", "Teasing", "Trembling",
    "Wailing", "Wincing", "Yelling", "Yawning", "Yearning",
    "Admiring", "Affectionate", "Amused", "Apologetic", "Astonished",
    "Awestruck", "Bashful", "Bewildered", "Bitter", "Blissful",
    "Boisterous", "Brooding", "Bubbly", "Calm", "Cheerful",
    "Chipper", "Compassionate", "Confident", "Contemplative", "Courageous",
    "Cynical", "Defensive", "Delirious", "Devious", "Doubtful",
    "Eager", "Ecstatic", "Elated", "Empathetic", "Enchanted",
    "Enraged", "Enthusiastic", "Exasperated", "Fascinated", "Fretful",
    "Fuming", "Generous", "Grateful", "Groggy", "Guilty",
    "Heartbroken", "Hysterical", "Indifferent", "Infuriated", "Innocent",
    "Inquisitive", "Inspired", "Intrigued", "Irritable", "Jaded",
    "Joyous", "Lively", "Loving", "Melancholic", "Mischievous",
    "Mournful", "Optimistic", "Outraged", "Overjoyed", "Passionate",
    "Pensive", "Perplexed", "Playful", "Pleased", "Proud",
    "Rapturous", "Regretful", "Rejoicing", "Relieved", "Remorseful",
    "Resigned", "Sentimental", "Sheepish", "Skeptical", "Sorrowful",
    "Startled", "Surly", "Sympathetic", "Tense", "Terrified",
    "Thoughtful", "Thrilled", "Tranquil", "Unsettled", "Vivacious",
    "Warmhearted", "Whimsical", "Wistful", "Woeful", "Zealous"
];

export const sports = [
    "Soccer", "Basketball", "Cricket", "Tennis", "Baseball",
    "American Football", "Rugby", "Golf", "Ice Hockey", "Volleyball",
    "Table Tennis", "Badminton", "Swimming", "Boxing", "Athletics",
    "Gymnastics", "Cycling", "Wrestling", "Martial Arts", "Judo",
    "Karate", "Taekwondo", "MMA", "Surfing", "Skateboarding",
    "Skiing", "Snowboarding", "Figure Skating", "Speed Skating", "Curling",
    "Bobsleigh", "Luge", "Skeleton", "Field Hockey", "Handball",
    "Water Polo", "Diving", "Rowing", "Canoeing", "Kayaking",
    "Sailing", "Archery", "Shooting", "Equestrian", "Triathlon",
    "Pentathlon", "Decathlon", "Weightlifting", "Powerlifting", "Bodybuilding",
    "Rock Climbing", "Mountaineering", "Hiking", "Fishing", "Hunting",
    "Motorsport", "Formula 1", "NASCAR", "Rally Racing", "Motorcycle Racing",
    "Horse Racing", "Greyhound Racing", "Polo", "Lacrosse", "Squash",
    "Racquetball", "Fencing", "Kendo", "Sumo Wrestling", "CrossFit",
    "Strongman", "Yoga", "Pilates", "Dance", "Cheerleading",
    "Parkour", "BMX", "Mountain Biking", "Enduro", "Trial Biking",
    "Freestyle Motocross", "Paragliding", "Skydiving", "Base Jumping", "Hang Gliding",
    "Bungee Jumping", "Cliff Diving", "Wakeboarding", "Water Skiing", "Jet Skiing",
    "Kitesurfing", "Windsurfing", "Synchronized Swimming", "Rhythmic Gymnastics", "Trampoline",
    "Roller Skating", "Inline Skating", "Roller Derby", "Softball", "Kickball",
    "Dodgeball", "Frisbee", "Ultimate Frisbee", "Disc Golf", "Orienteering",
    "Petanque", "Bocce", "Bowling", "Darts", "Snooker",
    "Billiards", "Air Hockey", "Foosball", "Shuffleboard", "Croquet",
    "Netball", "Rounders", "Tug of War", "Capture the Flag", "Quidditch",
    "Kabaddi", "Sepak Takraw", "Bossaball", "Tchoukball", "Padel Tennis",
    "Beach Tennis", "Beach Volleyball", "Sandboarding", "Sand Soccer", "Snow Volleyball",
    "Snow Polo", "Ice Climbing", "Ski Jumping", "Nordic Combined", "Biathlon",
    "Skeleton", "Para-athletics", "Para-swimming", "Wheelchair Basketball", "Sitting Volleyball",
    "Blind Soccer", "Goalball", "Adaptive Rowing", "Handcycling", "Para Powerlifting",
    "Wheelchair Fencing", "Para Taekwondo", "Para Judo", "Para Archery", "Para Shooting"
];

export const halloween = [
    "Trick or Treating", "Pumpkin Carving", "Haunted House", "Ghost",
    "Witch", "Vampire", "Werewolf", "Zombie", "Mummy", "Skeleton",
    "Black Cat", "Bat", "Spider", "Creepy Crawly", "Monster",
    "Graveyard", "Tombstone", "Coffin", "Jack-o'-Lantern", "Cauldron",
    "Potion", "Broomstick", "Full Moon", "Creepy Castle", "Spooky Forest",
    "Wearing a Costume", "Scaring Someone", "Making a Scary Face", "Lighting a Pumpkin", "Hiding Behind a Mask",
    "Dracula", "Frankenstein", "Ghoul", "Goblin", "Demon",
    "Sorcerer", "Magician", "Clown", "Phantom", "Poltergeist",
    "Alien", "Headless Horseman", "Boogeyman", "Wendigo", "Zombie Walk",
    "Casting a Spell", "Mixing a Potion", "Flying on a Broomstick", "Howling at the Moon", "Creeping Around",
    "Jumping Out", "Screaming", "Laughing Manically", "Evil Laughter", "Peeking from Behind a Corner",
    "Bobbing for Apples", "Telling a Ghost Story", "Reading a Spell Book", "Spinning a Web", "Walking Like a Zombie",
    "Haunting", "Lurking in the Shadows", "Creeping Up", "Playing a Prank", "Dressing Up",
    "Dancing like a Skeleton", "Clanking Chains", "Opening a Coffin", "Escaping a Grave", "Chasing Someone",
    "Stirring a Cauldron", "Floating", "Hiding in the Dark", "Knocking on Doors", "Running from a Monster",
    "Climbing a Wall", "Flickering Lights", "Creepy Music", "Stormy Night", "Eyeballs in a Jar",
    "Slime", "Magic Wand", "Blood", "Tattered Clothes", "Shadows",
    "Scary Mask", "Foggy Night", "Thunder and Lightning", "Cold Wind", "Creaking Door",
    "Haunted Doll", "Scream", "Eerie Sound", "Cemetery", "Haunted Mansion",
    "Ghostly Apparition", "Witch's Hat", "Bloodcurdling Scream", "Scary Movie", "Trick or Treat Bag",
    "Eyeball Soup", "Fright", "Scarecrow", "Cursed Object", "Witch's Brew",
    "Invisible Man", "Haunted Mirror", "Dark Alley", "Old House", "Mad Scientist",
    "Witch's Cat", "Creepy Doll", "Grinning Pumpkin", "Moonlit Night", "Spooky Shadow",
    "Scream Mask", "Glowing Eyes", "Cursed Book", "Horror Story", "Mystery",
    "Phantom Figure", "Skeleton Dance", "Cobwebs", "Scary Legend", "Burning Candles",
    "Jack-o'-Lantern Glow", "Mysterious Fog", "Halloween Party", "Creepy Crawlers", "Haunting Melody",
    "Gruesome", "Evil Spirit", "Dark Forest", "Gory", "Macabre",
    "Frightening", "Spooky Tale", "Horror House", "Blood Moon", "Frightful",
    "Ghoulish", "Eerie Silence", "Terrifying", "Sinister", "Menacing",
    "Nightmare", "Petrifying", "Bloodcurdling", "Creepiest", "Shadowy Figure",
    "Mysterious Footsteps", "Zombie Apocalypse", "Monster Mash", "Spooky Sound", "Ghostly Whisper",
    "Gravestone", "Spooky Silhouette", "Evil Grin", "Creaky Stairs", "Blood Stains",
    "Cursed Forest", "Fright Night", "Creepy Costumes", "Haunted Trail", "Doomed",
    "Scary Pranks", "Mysterious Disappearance", "Voodoo Doll", "Spooky Stories", "Scary Dreams",
    "Horrific", "Haunted Woods", "Ghost Hunt", "Night of Terror", "Sinister Laugh",
    "Terrifying Scream", "Evil Eyes", "Mystic", "Spooky Atmosphere", "Haunted Yard",
    "Creepy Crawlers", "Trick or Treaters", "Witchcraft", "Scary Sounds", "Creepy Crawlies",
    "Creepy Attic", "Dark Shadows", "Fog Machine", "Evil Witch", "Haunted Barn",
    "Eerie Glow", "Haunted Path", "Creepy Old Tree", "Mysterious Lights", "Creepy Hallway",
    "Scary Maze", "Graveyard Shift", "Creepy Laughter", "Gothic", "Haunted Bridge",
    "Spooky Dungeon", "Night Stalker", "Bone Chilling", "Blood Bath", "Phantom Ship",
    "Spooky Steps", "Skeletal Hands", "Dark Secret", "Creepy Woods", "Chilling Tales",
    "Creepy House", "Banshee Wail", "Creepy Basement", "Spooky Swamp", "Dark Castle",
    "Scary Decorations", "Haunted Garden", "Fright Fest", "Dark Magic", "Scary Silhouettes",
    "Creepy Vines", "Scary Maze", "Vampire Bite", "Witch's Lair", "Ghostly Visage",
    "Zombie Shuffle", "Spooky Scare", "Bloodcurdling Howl", "Gory Details", "Spooky Sounds",
    "Darkness Falls", "Mystical", "Spooky Skeleton", "Creepy Corridor", "Scary Movie Night",
    "Creepy Walk", "Gory Mask", "Creepy Window", "Phantom Screech", "Zombie Horde",
    "Ghastly", "Evil Laughter", "Creepy Whisper", "Cursed Room", "Shadowy Corners",
    "Grim Reaper", "Terrifying Monster", "Haunted Grave", "Creepy Murmur", "Spooky Wind",
    "Evil Shadows", "Creepy Giggle", "Frightened", "Gory Movie", "Chilling Scream",
    "Dark Forest Trail", "Scary Path", "Terrifying Tale", "Horrifying Scene", "Creepy Figures",
    "Scary Ghost", "Scary Creatures", "Haunted Objects", "Spooky Illusion", "Frightening Experience",
    "Eerie Shadows", "Ghostly Light", "Haunted Attic", "Creepy Encounter", "Spooky Park",
    "Creepy Closet", "Scary Book", "Mysterious Door", "Haunting Vision", "Dark Night",
    "Spooky Stare", "Creepy Grin", "Scary Haunted House", "Haunted Campfire", "Dark Cave",
    "Ghostly Encounter", "Witching Hour", "Scary Shadows", "Haunted Asylum", "Spooky Church",
    "Phantom Calls", "Scary Chase", "Dark Woods", "Spooky Images", "Ghostly Presence",
    "Spooky Howl", "Scary Place", "Chilling Effect", "Scary Alley", "Phantom Stories",
    "Haunting Presence", "Dark Night Sky", "Scary Face", "Eerie Moonlight", "Creepy Sound",
    "Phantom Sighting", "Spooky Tunes", "Scary Vibes", "Haunted History", "Dark Pathway",
    "Scary Shadows", "Spooky Forest Path", "Haunting Legends", "Creepy Ritual", "Scary Grave",
    "Dark Corners", "Ghost Story", "Haunted Maze", "Creepy Stairs", "Scary Experience",
    "Evil Ritual", "Dark Rituals", "Creepy Myths", "Haunting Myths", "Scary Forest",
    "Ghostly Orbs", "Scary Haunted", "Spooky Fair", "Creepy Lane", "Dark Passage",
    "Haunted Mansion Tour", "Spooky Carnival", "Scary Carnival", "Phantom Fair", "Creepy Tales"
];

export const professions = [
    "Doctor", "Nurse", "Teacher", "Engineer", "Software Developer",
    "Lawyer", "Accountant", "Architect", "Pharmacist", "Dentist",
    "Veterinarian", "Scientist", "Psychologist", "Electrician", "Plumber",
    "Mechanic", "Chef", "Police Officer", "Firefighter", "Paramedic",
    "Pilot", "Flight Attendant", "Farmer", "Journalist", "Photographer",
    "Actor", "Musician", "Artist", "Writer", "Librarian",
    "Social Worker", "Civil Engineer", "Environmental Engineer", "Biomedical Engineer", "Chemical Engineer",
    "Mechanical Engineer", "Industrial Engineer", "Aerospace Engineer", "Petroleum Engineer", "Geologist",
    "Meteorologist", "Astronomer", "Chemist", "Biologist", "Microbiologist",
    "Zoologist", "Botanist", "Ecologist", "Geneticist", "Marine Biologist",
    "Physical Therapist", "Occupational Therapist", "Speech Therapist", "Chiropractor", "Optometrist",
    "Audiologist", "Radiologist", "Surgeon", "Dermatologist", "Cardiologist",
    "Pediatrician", "Oncologist", "Psychiatrist", "Anesthesiologist", "Orthodontist",
    "Periodontist", "Prosthodontist", "Endodontist", "Dental Hygienist", "Dental Assistant",
    "Pharmacy Technician", "Medical Laboratory Technician", "Radiologic Technologist", "Nuclear Medicine Technologist", "Diagnostic Medical Sonographer",
    "Respiratory Therapist", "Surgical Technologist", "Veterinary Technician", "Veterinary Assistant", "Massage Therapist",
    "Athletic Trainer", "Exercise Physiologist", "Dietitian", "Nutritionist", "Health Educator",
    "Public Health Worker", "Epidemiologist", "Medical and Health Services Manager", "Healthcare Administrator", "Clinical Research Coordinator",
    "Medical Transcriptionist", "Medical Records Technician", "Medical Coder", "Medical Biller", "Home Health Aide",
    "Personal Care Aide", "Occupational Health and Safety Specialist", "Industrial Hygienist", "Environmental Scientist", "Environmental Engineer",
    "Urban Planner", "Surveyor", "Cartographer", "Geographer", "Hydrologist",
    "Conservation Scientist", "Forester", "Wildlife Biologist", "Fishery Biologist", "Soil Scientist",
    "Agricultural Engineer", "Agricultural Scientist", "Food Scientist", "Animal Scientist", "Plant Scientist",
    "Horticulturist", "Landscaper", "Groundskeeper", "Arborist", "Florist",
    "Landscape Architect", "Interior Designer", "Fashion Designer", "Graphic Designer", "Industrial Designer",
    "Multimedia Artist", "Animator", "Art Director", "Creative Director", "Advertising Manager",
    "Marketing Manager", "Public Relations Specialist", "Sales Manager", "Real Estate Agent", "Property Manager",
    "Insurance Agent", "Loan Officer", "Financial Advisor", "Financial Analyst", "Investment Banker",
    "Stockbroker", "Accountant", "Auditor", "Tax Preparer", "Budget Analyst",
    "Credit Analyst", "Actuary", "Economist", "Purchasing Manager", "Procurement Specialist",
    "Logistics Manager", "Supply Chain Manager", "Operations Manager", "Human Resources Manager", "Recruiter",
    "Training and Development Specialist", "Compensation and Benefits Manager", "Labor Relations Specialist", "Organizational Development Specialist", "IT Manager",
    "Network Administrator", "Database Administrator", "Systems Administrator", "Cybersecurity Specialist", "Information Security Analyst",
    "Web Developer", "Front-end Developer", "Back-end Developer", "Full-stack Developer", "Mobile App Developer",
    "Software Engineer", "Quality Assurance Analyst", "Business Analyst", "Data Analyst", "Data Scientist",
    "Machine Learning Engineer", "AI Specialist", "Cloud Engineer", "DevOps Engineer", "Systems Engineer",
    "Network Engineer", "IT Support Specialist", "Help Desk Technician", "Technical Support Specialist", "Computer Hardware Engineer",
    "Electronics Engineer", "Electrical Engineer", "Mechanical Engineer", "Civil Engineer", "Structural Engineer",
    "Construction Manager", "Project Manager", "Site Engineer", "Quantity Surveyor", "Building Inspector",
    "Plumber", "Electrician", "Carpenter", "Mason", "Painter",
    "Welder", "HVAC Technician", "Roofing Contractor", "Concrete Finisher", "Crane Operator"
];